### ISSUE TITLE
FFT-lora训练脚本96g显存也爆

### ISSUE THREAD

**Issue by CNEA-lw** [ali-vilab/ACE_plus#68]
我不知道是否是脚本或者是其他地方的问题，在我每一次修改训练脚本以及做其他优化时候，都会在第七个开始出现显存明显上升后爆显存的状况，下面是我的报错，请帮我查看问题，谢谢

**Comment by CNEA-lw** [comment]
![Image](https://github.com/user-attachments/assets/c09e98bf-cf56-4637-bc29-b4a6b6f58e95)

**Comment by maochaojie** [comment]
显存的影响因素可能是以下几个：
1、MAX_SEQ_LEN 这个是指的你输入的单张图片的seq大小限制（计算方式 H/16 * W/16），这个值越大，代表计算的sequence越长，训练的分辨率越大。我给的默认值是2048，如果可控生成的最大seq是 1*2048，如果参考生成或参考编辑的话，有一个参考图的情况下为 2*2048（1个参考图，1个生成图）。

![Image](https://github.com/user-attachments/assets/59e463e7-07cf-4486-99ee-f8d48f4ddb73)
2、attention的加速，我提供的计算attention的方式是使用flash_attn2，需要您检查一下flash_attn是不是安装成功了；如果torch版本是>2.4.0, torch原生是带有attention加速的，这个时候可以ATTN_BACKEND这个参数的设置为‘pytorch’。

![Image](https://github.com/user-attachments/assets/5b878911-1e09-41c7-b307-ca9793e88694)

3、使用Gradient Checkpoint也可以显著降低显存。
该参数可以加在2中参数下面，      
      # USE_GRAD_CHECKPOINT: setting gc to true can decrease the memory usage.
      USE_GRAD_CHECKPOINT: True

![Image](https://github.com/user-attachments/assets/73c49db5-0346-4684-af8c-8b60ec16fcaa)

按照上述参数，显存占用如下：
USE_GRAD_CHECKPOINT: False 时：
![Image](https://github.com/user-attachments/assets/34708a7d-5d9f-4fed-8fff-3dffbeae4478)
USE_GRAD_CHECKPOINT: True 时：

![Image](https://github.com/user-attachments/assets/cc2db46b-e8df-4cc6-b81f-757342322e88)

晚点我会在readme中说明这个问题。

**Comment by CNEA-lw** [comment]
> 显存的影响因素是以下几个： 1、MAX_SEQ_LEN 这个是指的你输入的单张图片的seq大小限制（计算方式 H/16 * W/16），这个值越大，代表计算的sequence越长，训练的分辨率越大。我给的默认值是2048，如果可控生成的最大seq是 1_2048，如果参考生成或参考编辑的话，有一个参考图的情况下为 2_2048（1个参考图，1个生成图）。
> 
> ![Image](https://github.com/user-attachments/assets/59e463e7-07cf-4486-99ee-f8d48f4ddb73) 2、attention的加速，我提供的计算attention的方式是使用flash_attn2，需要您检查一下flash_attn是不是安装成功了；如果torch版本是>2.4.0, torch原生是带有attention加速的，这个时候可以ATTN_BACKEND这个参数的设置为‘pytorch’。
> 
> ![Image](https://github.com/user-attachments/assets/5b878911-1e09-41c7-b307-ca9793e88694)
> 
> 3、使用Gradient Checkpoint也可以显著降低显存。 该参数可以加在2中参数下面， # USE_GRAD_CHECKPOINT: setting gc to true can decrease the memory usage. USE_GRAD_CHECKPOINT: True
> 
> ![Image](https://github.com/user-attachments/assets/bab30d44-4909-4676-af7a-baacf3411c12)
> 
> 按照上述参数，显存占用如下： USE_GRAD_CHECKPOINT: False 时： ![Image](https://github.com/user-attachments/assets/34708a7d-5d9f-4fed-8fff-3dffbeae4478) USE_GRAD_CHECKPOINT: True 时：
> 
> ![Image](https://github.com/user-attachments/assets/cc2db46b-e8df-4cc6-b81f-757342322e88)
> 
> 晚点我会在readme中说明这个问题。

辛苦你的努力，这个时间做出的回复，感谢！我在你的帮助下解决了显存上升强烈的问题，现在可以控制在38g内了，并且健康的训练，等待训练结束我将尝试拉高bath，后续有训练脚本上的优化麻烦@我或发布在项目中，感谢！

**Comment by prakhar-py** [comment]
@CNEA-lw I tried all the changes suggested by you but my code is still getting exploded after few hours i am using H100 gpu with 81559MiB VRAM. Why is this happening my training data is around 2 M images and eval data that i have given has 3700 images.

**Comment by hnsywangxin** [comment]
> [@CNEA-lw](https://github.com/CNEA-lw) I tried all the changes suggested by you but my code is still getting exploded after few hours i am using H100 gpu with 81559MiB VRAM. Why is this happening my training data is around 2 M images and eval data that i have given has 3700 images.

me too,I run python run_train.py  --cfg train_config/ace_plus_fft.yaml in a100 80G
